name: Build

on:
  push:
    tags: ['v*']
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25

      - name: Build ISO
        run: nix build .#packages.x86_64-linux.default

      - name: Upload ISO Artifact
        if: github.ref_type == 'branch'
        uses: actions/upload-artifact@v4
        with:
          name: t3-linux-iso
          path: result/iso/*.iso

      - name: Create Release
        if: github.ref_type == 'tag'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: result/iso/*.iso
          makeLatest: true
